name: deploy
on:
  push:
    branches: [main]

  pull_request:
    branches: [main]


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get the directory and files (Chekcout the repo)
        uses: actions/checkout@v4
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install dependencies
        run: pnpm install 
      - name: build application
        run: pnpm run build
      - name: run deployment script
        run: bash ./deploy.sh
          

