name: Terraform build
on:
  push:
    branches: [main]
    path:
      - terraform/**
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: terraform init
