name: Terraform build
on:
  push:
    branches: [main]

  pull_request:
    branches: [main]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Initializing terraform 
        uses: actions/checkout@v2
      - run: | 
            terraform init
            working-directory: ${{github.workspace}}/public

