name: Terraform build
on:
  push:
    branches: [main]

  pull_request:
    branches: [main]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      working-directory: terraform/** 
      - run: |
            terraform init
      
