name: Terraform build
on:
  push:
    branches: [main]

  pull_request:
    branches: [main]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Initializing terraform 
        working-directory: ${{github.workspace}}/public
        run: terraform init

