name: Terraform build
on:
  push:
    branches: [main]

  pull_request:
    branches: [main]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get the directory and files
        uses: actions/checkout@v2

        

      - name: Initializing terraform 
        env:
          tf_access_key_id :AWS_ACCESS_KEY_ID
          tf_secret_access_key_id :AWS_SECRET_ACCESS_KEY

        working-directory: ${{github.workspace}}/terraform
        run: terraform init
          

