name: Terraform build
on:
  push:
    branches: [main]

  pull_request:
    branches: [main]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - path: terraform/**
      - run: terraform init
      
