name: Terraform build
on:
  push:
    branches: [main]

  pull_request:
    branches: [main]


jobs:
  build:
    runs-on: ubuntu-latest
    working-directory: ${{github.workspace}}/public
    steps:
      - name: Initializing terraform 
        run: terraform init

